export const districts = [
  {
    name: "Bagerhat",
    cities: [
      { name: "Bagerhat Sadar" },
      { name: "Fakirhat" },
      { name: "Mollahat" },
      { name: "Kachua" },
      { name: "Chitalmari" },
      { name: "Rampal" },
      { name: "Mongla" },
      { name: "Morrelganj" },
      { name: "Sharankhola" },
    ],
  },
  {
    name: "Bandarban",
    cities: [
      { name: "Ali Kadam" },
      { name: "Bandarban Sadar" },
      { name: "Lama" },
      { name: "Naikhongchhari" },
      { name: "Rowangchhari" },
      { name: "Ruma" },
      { name: "Thanchi" },
    ],
  },
  {
    name: "Barguna",
    cities: [
      { name: "Barguna Sadar" },
      { name: "Amtali" },
      { name: "Bamna" },
      { name: "Patharghata" },
      { name: "Taltali" },
      { name: "Betagi" },
    ],
  },
  {
    name: "Barisal",
    cities: [
      { name: "Agailjhara" },
      { name: "Babuganj" },
      { name: "Bakerganj" },
      { name: "Banaripara" },
      { name: "Barisal Sadar" },
      { name: "Gournadi" },
      { name: "Hizla" },
      { name: "Mehendiganj" },
      { name: "Muladi" },
      { name: "Wazirpur" },
    ],
  },
  {
    name: "Bhola",
    cities: [
      { name: "Bhola Sadar" },
      { name: "Borhanuddin" },
      { name: "Char Fasson" },
      { name: "Daulatkhan" },
      { name: "Lalmohan" },
      { name: "Manpura" },
      { name: "Tazumuddin" },
    ],
  },
  {
    name: "Bogra",
    cities: [
      { name: "Adamdighi" },
      { name: "Bogra Sadar" },
      { name: "Sherpur" },
      { name: "Dhunat" },
      { name: "Dhupchanchia" },
      { name: "Gabtali" },
      { name: "Kahaloo" },
      { name: "Nandigram" },
      { name: "Shajahanpur" },
      { name: "Sariakandi" },
      { name: "Shibganj" },
      { name: "Sonatala" },
    ],
  },
  {
    name: "Brahmanbaria",
    cities: [
      { name: "Brahmanbaria Sadar" },
      { name: "Kasba" },
      { name: "Akhaura" },
      { name: "Ashuganj" },
      { name: "Bancharampur" },
      { name: "Bijoynagar" },
      { name: "Nasirnagar" },
      { name: "Nabinagar" },
      { name: "Sarail" },
    ],
  },
  {
    name: "Chandpur",
    cities: [
      { name: "Chandpur Sadar" },
      { name: "Hajiganj" },
      { name: "Shahrasti" },
      { name: "Haimchar" },
      { name: "Faridganj" },
      { name: "Kachua" },
      { name: "Matlab North (Matlab Uttar)" },
      { name: "Matlab South (Matlab Dakshin)" },
    ],
  },
  {
    name: "Chapai Nawabganj",
    cities: [
      { name: "Chapai Nawabganj Sadar" },
      { name: "Gomostapur" },
      { name: "Shibganj" },
      { name: "Bholahat" },
      { name: "Nachol" },
    ],
  },
  {
    name: "Chattogram",
    cities: [
      { name: "Anwara" },
      { name: "Banshkhali" },
      { name: "Boalkhali" },
      { name: "Chandanaish" },
      { name: "Fatikchhari" },
      { name: "Hathazari" },
      { name: "Lohagara" },
      { name: "Mirsharai" },
      { name: "Patiya" },
      { name: "Rangunia" },
      { name: "Raozan" },
      { name: "Sandwip" },
      { name: "Satkania" },
      { name: "Sitakunda" },
      { name: "Karnaphuli" }, // included with other upazila listings :contentReference[oaicite:1]{index=1}
    ],
  },
  {
    name: "Chuadanga",
    cities: [
      { name: "Alamdanga" },
      { name: "Chuadanga Sadar" },
      { name: "Damurhuda" },
      { name: "Jibannagar" },
    ],
  },
  {
    name: "Comilla",
    cities: [
      { name: "Barura" },
      { name: "Brahmanpara" },
      { name: "Burichong" },
      { name: "Comilla Sadar" },
      { name: "Comilla Sadar Dakshin" },
      { name: "Chandina" },
      { name: "Chauddagram" },
      { name: "Daudkandi" },
      { name: "Debidwar" },
      { name: "Homna" },
      { name: "Laksam" },
      { name: "Lalmai" },
      { name: "Monohorgonj" },
      { name: "Meghna" },
      { name: "Muradnagar" },
      { name: "Nangalkot" },
      { name: "Titas" },
    ],
  },
  {
    name: "Cox's Bazar",
    cities: [
      { name: "Kutubdia" },
      { name: "Pekua" },
      { name: "Maheshkhali" },
      { name: "Chakaria" },
      { name: "Cox's Bazar Sadar" },
      { name: "Eidgaon" },
      { name: "Ramu" },
      { name: "Ukhia" },
      { name: "Teknaf" },
    ],
  },
  {
    name: "Dhaka",
    cities: [
      { name: "Dhamrai" },
      { name: "Dohar" },
      { name: "Keraniganj" },
      { name: "Nawabganj" },
      { name: "Savar" },
    ],
  },
  {
    name: "Dinajpur",
    cities: [
      { name: "Biral" },
      { name: "Birampur" },
      { name: "Birganj" },
      { name: "Bochaganj" },
      { name: "Chirirbandar" },
      { name: "Dinajpur Sadar" },
      { name: "Fulbari" },
      { name: "Ghoraghat" },
      { name: "Hakimpur" },
      { name: "Kaharole" },
      { name: "Khansama" },
      { name: "Nawabganj" },
      { name: "Parbatipur" },
    ],
  },
  {
    name: "Faridpur",
    cities: [
      { name: "Alfadanga" },
      { name: "Bhanga" },
      { name: "Boalmari" },
      { name: "Charbhadrasan" },
      { name: "Faridpur Sadar" },
      { name: "Madhukhali" },
      { name: "Nagarkanda" },
      { name: "Sadarpur" },
      { name: "Saltha" },
    ],
  },
  {
    name: "Feni",
    cities: [
      { name: "Feni Sadar" },
      { name: "Daganbhuiyan" },
      { name: "Chhagalnaiya" },
      { name: "Parshuram" },
      { name: "Fulgazi" },
      { name: "Sonagazi" },
    ],
  },
  {
    name: "Gaibandha",
    cities: [
      { name: "Fulchhari" },
      { name: "Gaibandha Sadar" },
      { name: "Gobindaganj" },
      { name: "Palashbari" },
      { name: "Sadullapur" },
      { name: "Sundarganj" },
      { name: "Saghata" },
    ],
  },
  {
    name: "Gazipur",
    cities: [
      { name: "Gazipur Sadar" },
      { name: "Kaliakair" },
      { name: "Kaliganj" },
      { name: "Kapasia" },
      { name: "Sreepur" },
    ],
  },
  {
    name: "Gopalganj",
    cities: [
      { name: "Gopalganj Sadar" },
      { name: "Kotalipara" },
      { name: "Kasiani" },
      { name: "Muksudpur" },
      { name: "Tungipara" },
    ],
  },
  {
    name: "Habiganj",
    cities: [
      // Upazila data not retrieved yet—would follow once sourced
    ],
  },
  {
    name: "Jamalpur",
    cities: [
      { name: "Baksiganj" },
      { name: "Dewanganj" },
      { name: "Islampur" },
      { name: "Jamalpur Sadar" },
      { name: "Madarganj" },
      { name: "Melandaha" },
      { name: "Sarishabari" },
    ],
  },
  {
    name: "Jashore",
    cities: [
      { name: "Abhaynagar" },
      { name: "Bagherpara" },
      { name: "Chaugachha" },
      { name: "Jashore Sadar" },
      { name: "Jhikargachha" },
      { name: "Keshabpur" },
      { name: "Manirampur" },
      { name: "Sharsha" },
    ],
  },
  {
    name: "Jhalokati",
    cities: [
      { name: "Jhalokati Sadar" },
      { name: "Kathalia" },
      { name: "Nalchity" },
      { name: "Rajapur" },
    ],
  },
  {
    name: "Jhenaidah",
    cities: [
      { name: "Jhenaidah Sadar" },
      { name: "Maheshpur" },
      { name: "Kaliganj" },
      { name: "Kotchandpur" },
      { name: "Shailkupa" },
      { name: "Harinakunda" },
    ],
  },
  {
    name: "Joypurhat",
    cities: [
      { name: "Joypurhat Sadar" },
      { name: "Akkelpur" },
      { name: "Kalai" },
      { name: "Khetlal" },
      { name: "Panchbibi" },
    ],
  },
  {
    name: "Khagrachari",
    cities: [
      { name: "Khagrachhari Sadar" },
      { name: "Dighinala" },
      { name: "Mahalchari" },
      { name: "Panchhari" },
      { name: "Matiranga" },
      { name: "Manikchari" },
      { name: "Laxmichari" },
      { name: "Ramgarh" },
      { name: "Guimara" },
    ],
  },
  {
    name: "Khulna",
    cities: [
      { name: "Batiaghata" },
      { name: "Dacope" },
      { name: "Dighalia" },
      { name: "Dumuria" },
      { name: "Paikgachha" },
      { name: "Phultala" },
      { name: "Rupsa" },
      { name: "Terokhada" },
      { name: "Koyra" },
    ],
  },
  {
    name: "Kushtia",
    cities: [
      { name: "Kushtia Sadar" },
      { name: "Kumarkhali" },
      { name: "Khoksa" },
      { name: "Mirpur" },
      { name: "Bheramara" },
      { name: "Daulatpur" },
    ],
  },
  {
    name: "Kishoreganj",
    cities: [
      { name: "Kishoreganj Sadar" },
      { name: "Austagram" },
      { name: "Bajitpur" },
      { name: "Bhairab" },
      { name: "Hossainpur" },
      { name: "Itna" },
      { name: "Karimganj" },
      { name: "Katiadi" },
      { name: "Kuliarchar" },
      { name: "Mithamain" },
      { name: "Nikli" },
      { name: "Pakundia" },
      { name: "Tarail" },
    ],
  },
  {
    name: "Kurigram",
    cities: [
      { name: "Kurigram Sadar" },
      { name: "Phulbari" },
      { name: "Nageshwari" },
      { name: "Rajarhat" },
      { name: "Ulipur" },
      { name: "Chilmari" },
      { name: "Bhurungamari" },
      { name: "Char Rajibpur" },
      { name: "Rowmari" },
    ],
  },
  {
    name: "Lakshmipur",
    cities: [
      { name: "Lakshmipur Sadar" },
      { name: "Raipur" },
      { name: "Ramganj" },
      { name: "Ramgati" },
      { name: "Kamalnagar" },
    ],
  },
  {
    name: "Lalmonirhat",
    cities: [
      { name: "Lalmonirhat Sadar" },
      { name: "Aditmari" },
      { name: "Hatibandha" },
      { name: "Kaliganj" },
      { name: "Patgram" },
    ],
  },
  {
    name: "Madaripur",
    cities: [
      { name: "Madaripur Sadar" },
      { name: "Kalkini" },
      { name: "Rajoir" },
      { name: "Shibchar" },
      { name: "Dasar" },
    ],
  },
  {
    name: "Magura",
    cities: [
      { name: "Magura Sadar" },
      { name: "Mohammadpur" },
      { name: "Shalikha" },
      { name: "Sreepur" },
    ],
  },
  {
    name: "Manikganj",
    cities: [
      { name: "Manikganj Sadar" },
      { name: "Singair" },
      { name: "Daulatpur" },
      { name: "Shivalaya" },
      { name: "Ghior" },
      { name: "Harirampur" },
    ],
  },
  {
    name: "Meherpur",
    cities: [
      { name: "Meherpur Sadar" },
      { name: "Mujibnagar" },
      { name: "Gangni" },
    ],
  },
  {
    name: "Moulvibazar",
    cities: [
      { name: "Moulvibazar Sadar" },
      { name: "Sreemangal" },
      { name: "Kulaura" },
      { name: "Kamalganj" },
      { name: "Juri" },
      { name: "Barlekha" },
      { name: "Rajnagar" },
    ],
  },
  {
    name: "Munshiganj",
    cities: [
      { name: "Munshiganj Sadar" },
      { name: "Sreenagar" },
      { name: "Lohajang" },
      { name: "Sirajdikhan" },
      { name: "Tongibari" },
      { name: "Gazaria" },
    ],
  },
  {
    name: "Mymensingh",
    cities: [
      { name: "Mymensingh Sadar" },
      { name: "Muktagachha" },
      { name: "Bhaluka" },
      { name: "Fulbaria" },
      { name: "Gaffargaon" },
      { name: "Gouripur" },
      { name: "Nandail" },
      { name: "Haluaghat" },
      { name: "Ishwarganj" },
    ],
  },
  {
    name: "Naogaon",
    cities: [
      { name: "Naogaon Sadar" },
      { name: "Atrai" },
      { name: "Badalgachhi" },
      { name: "Dhamoirhat" },
      { name: "Manda" },
      { name: "Mohadevpur" },
      { name: "Niamatpur" },
      { name: "Raninagar" },
      { name: "Patnitala" },
    ],
  },
  {
    name: "Narail",
    cities: [{ name: "Narail Sadar" }, { name: "Lohagara" }, { name: "Kalia" }],
  },
  {
    name: "Narayanganj",
    cities: [
      { name: "Narayanganj Sadar" },
      { name: "Rupganj" },
      { name: "Araihazar" },
      { name: "Sonargaon" },
      { name: "Bandar Upazila" },
    ],
  },
  {
    name: "Narsingdi",
    cities: [
      { name: "Narsingdi Sadar" },
      { name: "Palash" },
      { name: "Belabo" },
      { name: "Monohardi" },
      { name: "Raipura" },
    ],
  },
  {
    name: "Natore",
    cities: [
      { name: "Natore Sadar" },
      { name: "Bagatipara" },
      { name: "Baraigram" },
      { name: "Lalpur" },
      { name: "Natore Sadar Upozila" }, // Duplicate naming as Sadar perhaps, but included logically
    ],
  },
  {
    name: "Netrokona",
    cities: [
      { name: "Netrokona Sadar" },
      { name: "Kendua" },
      { name: "Atpara" },
      { name: "Mohanganj" },
      { name: "Barhatta" },
      { name: "Durgapur" },
      { name: "Kalmakanda" },
      { name: "Madan" },
    ],
  },
  {
    name: "Nilphamari",
    cities: [
      { name: "Nilphamari Sadar" },
      { name: "Jaldhaka" },
      { name: "Dimla" },
      { name: "Domar" },
      { name: "Saidpur" },
    ],
  },
  {
    name: "Noakhali",
    cities: [
      { name: "Noakhali Sadar" },
      { name: "Begumganj" },
      { name: "Chatkhil" },
      { name: "Companiganj" },
      { name: "Hatiya" },
      { name: "Kabirhat" },
      { name: "Senbagh" },
      { name: "Sonaimuri" },
      { name: "Subarnachar" },
    ],
  },
  {
    name: "Pabna",
    cities: [
      { name: "Atgharia" },
      { name: "Bera" },
      { name: "Bhangura" },
      { name: "Chatmohar" },
      { name: "Faridpur" },
      { name: "Ishwardi" },
      { name: "Pabna Sadar" },
      { name: "Santhia" },
      { name: "Sujanagar" },
    ],
  },
  {
    name: "Panchagarh",
    cities: [
      { name: "Panchagarh Sadar" },
      { name: "Debiganj" },
      { name: "Boda" },
      { name: "Atwari" },
      { name: "Tetulia" },
    ],
  },
  {
    name: "Patuakhali",
    cities: [
      { name: "Dumki" },
      { name: "Patuakhali Sadar" },
      { name: "Mirzaganj" },
      { name: "Bauphal" },
      { name: "Galachipa" },
      { name: "Dashmina" },
      { name: "Rangabali" },
      { name: "Kalapara" },
    ],
  },
  {
    name: "Pirojpur",
    cities: [
      { name: "Pirojpur Sadar" },
      { name: "Bhandaria" },
      { name: "Mathbaria" },
      { name: "Indurkani" },
      { name: "Nazirpur" },
      { name: "Nesarabad (Swarupkati)" },
      { name: "Kawkhali" },
    ],
  },
  {
    name: "Rajbari",
    cities: [
      { name: "Rajbari Sadar" },
      { name: "Pangsha" },
      { name: "Goalanda" },
      { name: "Baliakandi" },
      { name: "Kalukhali" },
    ],
  },
  {
    name: "Rajshahi",
    cities: [
      { name: "Bagha" },
      { name: "Bagmara" },
      { name: "Charghat" },
      { name: "Durgapur" },
      { name: "Godagari" },
      { name: "Mohanpur" },
      { name: "Paba" },
      { name: "Puthia" },
      { name: "Tanore" },
    ],
  },
  {
    name: "Rangamati",
    cities: [
      { name: "Rangamati Sadar" },
      { name: "Bagaichhari" },
      { name: "Barkal" },
      { name: "Belaichhari" },
      { name: "Juraichhari" },
      { name: "Rajasthali" },
      { name: "Kaptai" },
      { name: "Kawkhali" },
      { name: "Langadu" },
      { name: "Naniarchar" },
    ],
  },
  {
    name: "Rangpur",
    cities: [
      { name: "Rangpur Sadar" },
      { name: "Badarganj" },
      { name: "Kaunia" },
      { name: "Gangachhara" },
      { name: "Mithapukur" },
      { name: "Pirgacha" },
      { name: "Taraganj" },
    ],
  },
  {
    name: "Satkhira",
    cities: [
      { name: "Satkhira Sadar" },
      { name: "Assasuni" },
      { name: "Debhata" },
      { name: "Kalaroa" },
      { name: "Kaliganj" },
      { name: "Shyamnagar" },
      { name: "Tala" },
    ],
  },
  {
    name: "Shariatpur",
    cities: [
      { name: "Shariatpur Sadar" },
      { name: "Damudya" },
      { name: "Naria" },
      { name: "Zanjira" },
      { name: "Bhedarganj" },
      { name: "Gosairhat" },
    ],
  },
  {
    name: "Sherpur",
    cities: [
      { name: "Sherpur Sadar" },
      { name: "Nalitabari" },
      { name: "Sreebardi" },
      { name: "Jhenaigati" },
      { name: "Nakla" },
    ],
  },
  {
    name: "Sirajganj",
    cities: [
      { name: "Sirajganj Sadar" },
      { name: "Kazipur" },
      { name: "Ullahpara" },
      { name: "Shahjadpur" },
      { name: "Raiganj" },
      { name: "Kamarkhanda" },
      { name: "Tarash" },
      { name: "Belkuchi" },
      { name: "Chauhali" },
    ],
  },
  {
    name: "Sunamganj",
    cities: [
      { name: "Sunamganj Sadar" },
      { name: "Derai" },
      { name: "Chhatak" },
      { name: "Dharamapasha" },
      { name: "Dowarabazar" },
      { name: "Jagannathpur" },
      { name: "Jamalganj" },
      { name: "Madhyanagar" },
      { name: "Shalla" },
      { name: "Shantiganj" },
      { name: "Tahirpur" },
    ],
  },
  {
    name: "Sylhet",
    cities: [
      { name: "Balaganj" },
      { name: "Beanibazar" },
      { name: "Bishwanath" },
      { name: "Companiganj" },
      { name: "Dakshin Surma" },
      { name: "Fenchuganj" },
      { name: "Golapganj" },
      { name: "Gowainghat" },
      { name: "Jaintiapur" },
      { name: "Kanaighat" },
      { name: "Osmani Nagar" },
      { name: "Sylhet Sadar" },
      { name: "Zakiganj" },
    ],
  },
  {
    name: "Tangail",
    cities: [
      { name: "Tangail Sadar" },
      { name: "Sakhipur" },
      { name: "Basail" },
      { name: "Madhupur" },
      { name: "Ghatail" },
      { name: "Kalihati" },
      { name: "Nagarpur" },
      { name: "Mirzapur" },
      { name: "Gopalpur" },
      { name: "Delduar" },
      { name: "Bhuapur" },
      { name: "Dhanbari" },
    ],
  },
  {
    name: "Thakurgaon",
    cities: [
      { name: "Thakurgaon Sadar" },
      { name: "Baliadangi" },
      { name: "Haripur" },
      { name: "Ranisankail" },
      { name: "Pirganj" },
    ],
  },
];
