export const listings = [
  {
    id: "1",
    title: "2 Bedroom Apartment in Dhanmondi",
    address: {
      street: "House 12, Road 7",
      area: "Dhanmondi",
      city: "Dhaka",
      zipCode: "1209",
    },
    rent: 25000,
    size_sft: 950,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    floor: 3,
    available_from: "2025-07-01",
    features: ["Lift", "Generator", "Security Guard", "Parking"],
    images: [
      "/images/listings/dhanmondi1_1.jpg",
      "/images/listings/dhanmondi1_2.jpg",
    ],
    contact: {
      name: "Md. Rahim",
      phone: "017xxxxxxxx",
      email: "rahim@example.com",
    },
    posted_at: "2025-06-15T10:30:00Z",
  },
  {
    id: "2",
    title: "Single Room for Bachelor in Mirpur",
    address: {
      street: "Block C, Mirpur 10",
      area: "Mirpur",
      city: "Dhaka",
      zipCode: "1216",
    },
    rent: 6000,
    size_sft: 200,
    bedrooms: 1,
    bathrooms: 1,
    balconies: 0,
    floor: 5,
    available_from: "2025-06-20",
    features: ["24h Water", "Security Guard"],
    images: ["/images/listings/mirpur1_1.jpg"],
    contact: {
      name: "Sadia Akter",
      phone: "018xxxxxxxx",
      email: "sadia@example.com",
    },
    posted_at: "2025-06-10T08:00:00Z",
  },
  {
    id: "3",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
  {
    id: "4",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
  {
    id: "5",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
  {
    id: "6",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
  {
    id: "7",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
  {
    id: "8",
    title: "3 Bedroom Flat with Parking in Uttara",
    address: {
      street: "Sector 11, Road 5",
      area: "Uttara",
      city: "Dhaka",
      zipCode: "1230",
    },
    rent: 40000,
    size_sft: 1350,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    floor: 6,
    available_from: "2025-07-10",
    features: ["Lift", "Generator", "Parking", "Community Hall"],
    images: [
      "/images/listings/uttara1_1.jpg",
      "/images/listings/uttara1_2.jpg",
      "/images/listings/uttara1_3.jpg",
    ],
    contact: {
      name: "Karim Hossain",
      phone: "016xxxxxxxx",
      email: "karim@example.com",
    },
    posted_at: "2025-06-12T12:45:00Z",
  },
];
